# Práctica de Numpy

In [4]:
import numpy as  np # así se importa la librería numpy

## Creación básica de arrays

In [9]:
a=np.array(13) #array de dimensión 0
b=np.array([1,2,3,4]) #array de dimensión 1
c=np.array([[1,2,3,4],[5,6,7,8]]) #array de dimensión 2. 
d=np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]]) #array de dimensión 3. Son 3 listas

print("a =",a,"\n")
print(a.shape)
print("b =",b,"\n")
print(b.shape)
print("c =",c,"\n")
print(c.shape)
print("d =",d,"\n")
print(d.shape)


a = 13 

()
b = [1 2 3 4] 

(4,)
c = [[1 2 3 4]
 [5 6 7 8]] 

(2, 4)
d = [[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]] 

(2, 2, 4)


Se pueden observar las dimensiones de los arreglos
Por ejemplo, para el objeto d, se tiene que es de 2 x 2 x 4. Esto es, 2 listas que contienen 2 listas cada una, con 4 elementos en cada una de ellas.

In [ ]:
# Revisando ahora las dimensiones como tal:
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

## Indexación básica

In [10]:
a[0] # produce un error porque es un objeto de dimensión 0

IndexError: too many indices for array: array is 0-dimensional, but 1 were indexed

In [13]:
b[1] # obtengo el segundo elemento del arreglo, que resulta ser el número 2

2

In [15]:
d[1][0] # Aquí obtengo la segunda lista (entre las dos más grandes), y luego obtengo la primera lista de ella.

array([ 9, 10, 11, 12])

In [16]:
d[1][0][1] # Aquí obtengo el número 10, accediendo al segundo elemento de la consulta anterior

10

In [24]:
d[0,:]  # Estoy obteniendo todos los elementos (2 arreglos) del primer arreglo 

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

## Algunas funciones aplicadas a arrays

In [75]:
e = np.array([[4,56,-3,5,7],[-6,0,1,6,3]])
print(e)
print("")
print(e.argmax()) # Me dice que el mayor valor se encuentra en la segunda posición (56)
print(e.argmin())  # Análogamente, en la sexta posición se encuentra el menor valor (-6)

[[ 4 56 -3  5  7]
 [-6  0  1  6  3]]

1
5


In [77]:
e.cumsum()  # Esto hace que los elementos se vayan sumando término a término (cumulative sum)

array([ 4, 60, 57, 62, 69, 63, 63, 64, 70, 73])

In [87]:
e.sum()  # Me da la suma final.

73

In [79]:
e.mean() #obtengo la media 

7.3

In [84]:
e.sort()  # Me ordena la base. Como tengo dos arrays, me ordena cada array de menor a mayor
e

array([[-3,  4,  5,  7, 56],
       [-6,  0,  1,  3,  6]])

In [85]:
e.std()

16.685622553563892

## Diferentes tipos de datos en los arrays

In [27]:
# Se creará un arreglo de strings
frutas = np.array(["Uva","Fresa", "Naranja"])
frutas

array(['Uva', 'Fresa', 'Naranja'], dtype='<U7')

In [32]:
frutas

array([b'Uva', b'Fresa', b'Naranja'], dtype='|S7')

In [33]:
# Puedo hacer coerciones
numeros = np.array(["2","6","1"])
numeros.astype("S") #Aquí los convierto a tipo string

array([b'2', b'6', b'1'], dtype='|S1')

In [39]:
floating_array = np.array([1.1, 2.1, 3.99]) #punto flotante

int_array = floating_array.astype('i') # Lo coerciono para que sea integer. Redondea siempre hacia abajo
print(int_array)

[1 2 3]


## Reformar arrays
Se puede cambiar la forma de los arrays. Esto es, cambiar la dimensión o cambiar el número de elementos por dimensión.

In [41]:
d.reshape(2,8)

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16]])

In [42]:
# Si intento cambiarlo a una forma que es imposible, saldrá error.
# el array d tiene 16 elementos, luego, no puedo cambiarlo a 1 dimensión de 8 elementos. Saldrá error
d.reshape(1,8)

ValueError: cannot reshape array of size 16 into shape (1,8)

In [43]:
d.reshape(4,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

### Dimensión desconocida
Con el -1 se indica a numpoy que acomode los datos a la forma en que mejor se ajusten...

In [46]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
arr_nuevo = arr.reshape(3,-1)
arr_nuevo

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [48]:
# Con el argumento .T hacemos la transpuesta
print(arr_nuevo)
print("")
print(arr_nuevo.T)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 4 7]
 [2 5 8]
 [3 6 9]]


## Iterar arrays

In [51]:
for x in d:
    print(x)
print("")
print(d)

[[1 2 3 4]
 [5 6 7 8]]
[[ 9 10 11 12]
 [13 14 15 16]]

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]


In [52]:
# Si se quiere iterar cada elemento, se necesita un for para cada dimensión:
for x in d:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16


Puesto que eso no es lo más adecuado, numpy tiene la función np.nditer

In [54]:
for x in np.nditer(d):
    print(x)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16


## Operaciones con arrays

### Suma
numpy tiene dos funciones, np.add() y np.sum(). El primero se aplica entre argumentos, el segundo se aplica en n elementos para que se haga la suma, es necesario que ambos arrays tengan la misma forma

In [55]:
arr1=np.array([[1,2,3],
               [4,5,6]])
arr2=np.array([[6,5,4],
               [3,2,1]])
np.add(arr1,arr2)

array([[7, 7, 7],
       [7, 7, 7]])

In [56]:
arr1 + arr2  # también funciona con el +

array([[7, 7, 7],
       [7, 7, 7]])

In [57]:
arr3=np.array([[1,1,1],[1,1,1]])
print(np.sum([arr1,arr2]))  # se suman todos los elementos y da un escalar.
print(np.sum([arr1,arr2,arr3]))

42
48


## Multiplicación
El primer caso de multiplicación es np.prod(), que funciona similar que np.sum()

In [58]:
np.prod([arr1,arr2]) # Me da un escalar

518400

## Multiplicación matricial
Para la multiplicación de matrices usamos np.matmul() o np.dot(). hay que tener en cuenta la forma de las matrices

In [65]:
print(arr1)
print("")
print(arr2.T)
print("")
np.matmul(arr1, arr2.T)

[[1 2 3]
 [4 5 6]]

[[6 3]
 [5 2]
 [4 1]]



array([[28, 10],
       [73, 28]])

In [67]:
print(np.dot(d[0],d.reshape(2,4,2)[0]),"\n")
print(np.dot(d[0],d.reshape(2,4,2)[1]),"\n")
print(np.dot(d[1],d.reshape(2,4,2)[0]),"\n")
print(np.dot(d[1],d.reshape(2,4,2)[1]),"\n")

[[ 50  60]
 [114 140]] 

[[130 140]
 [322 348]] 

[[178 220]
 [242 300]] 

[[514 556]
 [706 764]] 



Con matmul no se pueden multiplicar escalares c.A (c escalar, A matriz), además Matmul hace las multiplicaciones matriz a matriz (matrices como elementos), de ahí la diferencia con dot, donde este toma los números dentro de las matrices como elementos.

In [68]:
np.matmul(d,d.reshape(2,4,2))

array([[[ 50,  60],
        [114, 140]],

       [[514, 556],
        [706, 764]]])